function iconForEntry(fileName, fileIsDir, fileSuffix) {
    if (fileIsDir) {
        return "folder";
    }

    const ext = (fileSuffix || "").toLowerCase();

    switch (ext) {
    case "jpg":
    case "jpeg":
    case "png":
    case "gif":
    case "webp":
    case "svg":
    case "bmp":
    case "ico":
    case "tiff":
    case "tif":
    case "avif":
    case "heic":
    case "heif":
    case "raw":
    case "cr2":
    case "nef":
        return "image";
    case "mp4":
    case "mkv":
    case "avi":
    case "mov":
    case "webm":
    case "flv":
    case "wmv":
    case "mpg":
    case "mpeg":
    case "m4v":
    case "3gp":
        return "movie";
    case "mp3":
    case "flac":
    case "wav":
    case "ogg":
    case "m4a":
    case "aac":
    case "opus":
    case "wma":
    case "aiff":
    case "alac":
        return "music_note";
    case "pdf":
        return "picture_as_pdf";
    case "zip":
    case "tar":
    case "gz":
    case "bz2":
    case "xz":
    case "7z":
    case "rar":
    case "lz":
    case "zst":
    case "lz4":
    case "br":
        return "inventory_2";
    case "js":
    case "ts":
    case "py":
    case "cpp":
    case "c":
    case "h":
    case "hpp":
    case "rs":
    case "go":
    case "java":
    case "kt":
    case "swift":
    case "rb":
    case "php":
    case "sh":
    case "bash":
    case "zsh":
    case "pl":
    case "lua":
    case "r":
    case "m":
    case "mm":
    case "dart":
    case "groovy":
    case "scala":
    case "clj":
    case "ex":
    case "exs":
    case "erl":
    case "hrl":
    case "elm":
    case "fs":
    case "fsx":
    case "ml":
    case "mli":
    case "pas":
    case "pp":
    case "d":
    case "nim":
    case "cr":
    case "v":
    case "zig":
    case "odin":
    case "jl":
        return "code";
    case "html":
    case "htm":
    case "css":
    case "qml":
    case "jsx":
    case "tsx":
    case "vue":
    case "svelte":
    case "scss":
    case "sass":
    case "less":
    case "styl":
    case "pcss":
        return "code";
    case "md":
    case "txt":
    case "rst":
    case "log":
    case "nfo":
    case "info":
    case "tex":
    case "org":
        return "description";
    case "doc":
    case "docx":
    case "odt":
    case "rtf":
    case "pages":
        return "description";
    case "xls":
    case "xlsx":
    case "ods":
    case "csv":
    case "tsv":
        return "table_chart";
    case "ppt":
    case "pptx":
    case "odp":
    case "key":
        return "slideshow";
    case "json":
    case "xml":
    case "yaml":
    case "yml":
    case "toml":
    case "ini":
    case "cfg":
    case "conf":
    case "env":
    case "properties":
        return "data_object";
    case "db":
    case "sqlite":
    case "sqlite3":
    case "mdb":
    case "accdb":
        return "database";
    case "iso":
    case "img":
    case "dmg":
    case "vmdk":
    case "qcow2":
        return "album";
    case "ttf":
    case "otf":
    case "woff":
    case "woff2":
    case "eot":
        return "font_download";
    case "apk":
    case "deb":
    case "rpm":
    case "pkg":
    case "msi":
    case "exe":
    case "dmg":
    case "appimage":
    case "snap":
    case "flatpak":
        return "apps";
    case "crt":
    case "pem":
    case "key":
    case "pub":
    case "gpg":
    case "asc":
        return "vpn_key";
    default:
        return "description";
    }
}

function iconForShortcut(name) {
    switch (name) {
    case "Home":
        return "home";
    case "Desktop":
        return "desktop_windows";
    case "Documents":
        return "description";
    case "Downloads":
        return "download";
    case "Pictures":
        return "image";
    case "Music":
        return "music_note";
    case "Videos":
        return "movie";
    case "Trash":
        return "delete";
    default:
        return "folder";
    }
}
